### ISSUE TITLE
Control character inside non-first key in large multi-get request will cause mcrouter to crash

### ISSUE THREAD

**Issue by hrjaco** [facebook/mcrouter#95] opened 2015-12-03 00:42 UTC
We saw some McRouter crashes in our production recently. The crash failed at:
lib/mc/ascii_client.rl:575: _on_ascii_rx: Assertion `parser->msg' failed.

After some investigation, we found the request to mcrouter is a large multi-get(batch of 400), and contains control character in one key. Although this is a bad request, McRouter should handle it gracefully instead of crashing.

Below is the step to reproduce it in ipython using pymemcache client:
$ from pymemcache.client import Client
$ c = Client(('localhost', 22000))  # McRouter runs at port 22000
$ l = range(1,500)
$ emails = map(lambda i: 'contact:email:' + str(i), l)
$ emails[1] = emails[1] + '\t'
$ c.get_many(emails)

Some interesting findings:
1. This trigger factor is not large batch, but when the length of the request exceeds ~2048.
If the request can fit into one IOBuf, McRouter wont crash.
2. If the first key contains control character, McRouter also wont crash.

**Comment by jmswen** [comment] 2015-12-08 02:50
Hi @hrjaco, thank you for reporting this.  Can you let me know which version of mcrouter you're using?  Even approximately when the checkout is from is fine.  We believe this issue should be fixed in recent versions, and I am unable to reproduce this crashing behavior with a recent version.  Thanks.

**Comment by hrjaco** [comment] 2015-12-08 19:45
We are using version 2:0 https://github.com/facebook/mcrouter/commit/8303e732b94469d213266dc512cece4860875305 with the Trie optimization change(https://github.com/facebook/mcrouter/commit/0fdc0b6a36bec345390a30d34b2f1a36751c033b) reverted.

**Comment by jmswen** [comment] 2015-12-09 21:50
@hrjaco Thanks for letting me know.  This issue is fixed by our new ASCII parser, which is currently available in master or the release-14-0 branch

**Closed by jmswen** 2015-12-09 21:50 UTC
